version: "3"    

services:
    server_api:
        build: .
        restart: always
        network_mode: host
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
        environment:
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DB=${POSTGRES_DB}
        container_name: api-back
        depends_on:
            - postgresql
        command: build

    postgresql:
        image: postgres
        container_name: postgres
        restart: always
        environment: 
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DB=${POSTGRES_DB}
                - AWS_ACCESS_KEY_ID=${POSTGRES_DB}
                - AWS_S3_ENDPOINT_URL=${POSTGRES_DB}
                - AWS_S3_REGION_NAME=${POSTGRES_DB}
                - AWS_SECRET_ACCESS_KEY=${POSTGRES_DB}
                - AWS_STORAGE_BUCKET_NAME=${POSTGRES_DB}
                - SECRET_KEY=${SECRET_KEY}
        ports:
                - 5432:5432
        expose:
                - '5432'