version: "3"    

volumes:
        postgres_data:

services:
    server_api:
        build: .
        restart: always
        network_mode: host
        volumes:
            - ./src:/app/src
            - ./tests:/app/tests
        environment:
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DB=${POSTGRES_DB}
        container_name: api-back
        depends_on:
            - postgresql
        command: build

    postgresql:
        image: postgres
        container_name: postgres
        restart: always
        environment: 
                - POSTGRES_USER=${POSTGRES_USER}
                - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
                - POSTGRES_DB=${POSTGRES_DB}
        volumes:
                - ./postgres_data:/var/lib/postgresql/data/
        ports:
                - 5432:5432
        expose:
                - '5432'