# Generated by Django 3.1.7 on 2021-02-20 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_s3_storage.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('animal_type', models.CharField(blank=True, max_length=15, null=True)),
                ('breed', models.CharField(blank=True, max_length=30, null=True)),
                ('color', models.CharField(blank=True, max_length=15, null=True)),
                ('sex', models.CharField(blank=True, choices=[('woman', 'woman'), ('man', 'man')], default='man', max_length=5, null=True)),
                ('description', models.CharField(blank=True, max_length=600, null=True)),
                ('animal_features', models.JSONField(blank=True, default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adverts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_url', models.ImageField(storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='squaredanimals'), upload_to='')),
                ('advert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='advert.advert')),
            ],
        ),
    ]
