# Generated by Django 3.1.7 on 2021-02-20 16:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('photo_urls', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=5)),
                ('animal_type', models.CharField(max_length=15)),
                ('breed', models.CharField(max_length=30)),
                ('color', models.CharField(max_length=15)),
                ('sex', models.CharField(choices=[('woman', 'woman'), ('man', 'man')], max_length=5)),
                ('description', models.CharField(max_length=600)),
            ],
        ),
    ]
