# Generated by Django 3.1.7 on 2021-02-20 18:01

from django.db import migrations, models
import django_s3_storage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('advert', '0002_auto_20210220_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='photo_urls',
            field=models.ImageField(null=True, storage=django_s3_storage.storage.S3Storage(aws_s3_bucket_name='8streams'), upload_to=''),
        ),
    ]
